source 'https://rubygems.org'

gem 'unicorn', '~> 4.8.2'
gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise', '3.5.4'
gem 'will_paginate', '~> 3.0.7'
gem 'will_paginate-bootstrap'
gem 'pg'
gem 'pg_search', '~> 0.7.6'
gem 'therubyracer', platforms: :ruby
gem 'simple_form', '~> 3.2.1'
gem 'cancancan', '~> 1.13.1'
gem 'judge-simple_form'
gem 'font-awesome-rails'
gem 'select2-rails', '~> 3.5.9.3'
gem 'jquery-turbolinks'
gem 'delocalize', '~> 1.0.0'
gem 'nested_form'
gem "paperclip"
gem "twitter-bootstrap-rails"

group :development, :test do
  gem 'thin'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'guard-rspec'#, '0.5.5'
  gem 'spork', '1.0.0rc4'
  gem 'guard-spork'
  gem 'simplecov'
  gem 'better_errors'
  gem "binding_of_caller", "~> 0.7.2"
  gem 'quiet_assets'
  gem 'dotenv-rails'
  gem 'rails_layout'
  gem 'faker'
  gem "launchy"
  gem 'database_cleaner'
  gem 'spring'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
end

group :development do
  gem 'bullet'
  gem 'letter_opener'
  gem 'i18n-tasks', '~> 0.8.3'
end

group :test do
  gem 'webmock'
  gem 'capybara-email'
  gem 'email_spec'
  gem "capybara-webkit", "~> 1.7.1"
  gem 'parallel_tests'
  gem 'shoulda-matchers'
  gem 'shoulda-callback-matchers', '~> 1.1.1'
end

group :production, :staging  do
  # gem 'heroku-deflater'
  gem 'heroku_rails_deflate'
  gem 'rails_12factor'
end
